// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/relationship/ouvinteseguirartista/interface.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	entity "github.com/yohanalexander/deezefy-music/entity"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Seguir mocks base method
func (m *MockUseCase) Seguir(o *entity.Ouvinte, a *entity.Artista) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seguir", o, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Seguir indicates an expected call of Seguir
func (mr *MockUseCaseMockRecorder) Seguir(o, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seguir", reflect.TypeOf((*MockUseCase)(nil).Seguir), o, a)
}

// Desseguir mocks base method
func (m *MockUseCase) Desseguir(o *entity.Ouvinte, a *entity.Artista) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Desseguir", o, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Desseguir indicates an expected call of Desseguir
func (mr *MockUseCaseMockRecorder) Desseguir(o, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Desseguir", reflect.TypeOf((*MockUseCase)(nil).Desseguir), o, a)
}
