// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/musica/interface.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	musica "github.com/yohanalexander/deezefy-music/entity/musica"
	reflect "reflect"
)

// MockMusica is a mock of Musica interface
type MockMusica struct {
	ctrl     *gomock.Controller
	recorder *MockMusicaMockRecorder
}

// MockMusicaMockRecorder is the mock recorder for MockMusica
type MockMusicaMockRecorder struct {
	mock *MockMusica
}

// NewMockMusica creates a new mock instance
func NewMockMusica(ctrl *gomock.Controller) *MockMusica {
	mock := &MockMusica{ctrl: ctrl}
	mock.recorder = &MockMusicaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMusica) EXPECT() *MockMusicaMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockMusica) Get(id int) (*musica.Musica, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*musica.Musica)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockMusicaMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMusica)(nil).Get), id)
}

// Search mocks base method
func (m *MockMusica) Search(query string) ([]*musica.Musica, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", query)
	ret0, _ := ret[0].([]*musica.Musica)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockMusicaMockRecorder) Search(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockMusica)(nil).Search), query)
}

// List mocks base method
func (m *MockMusica) List() ([]*musica.Musica, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*musica.Musica)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockMusicaMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMusica)(nil).List))
}

// Create mocks base method
func (m *MockMusica) Create(e *musica.Musica) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", e)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockMusicaMockRecorder) Create(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMusica)(nil).Create), e)
}

// Update mocks base method
func (m *MockMusica) Update(e *musica.Musica) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockMusicaMockRecorder) Update(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMusica)(nil).Update), e)
}

// Delete mocks base method
func (m *MockMusica) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockMusicaMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMusica)(nil).Delete), id)
}

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockRepository) Get(id int) (*musica.Musica, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*musica.Musica)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockRepositoryMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), id)
}

// Search mocks base method
func (m *MockRepository) Search(query string) ([]*musica.Musica, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", query)
	ret0, _ := ret[0].([]*musica.Musica)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockRepositoryMockRecorder) Search(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRepository)(nil).Search), query)
}

// List mocks base method
func (m *MockRepository) List() ([]*musica.Musica, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*musica.Musica)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List))
}

// Create mocks base method
func (m *MockRepository) Create(e *musica.Musica) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", e)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockRepositoryMockRecorder) Create(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), e)
}

// Update mocks base method
func (m *MockRepository) Update(e *musica.Musica) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockRepositoryMockRecorder) Update(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), e)
}

// Delete mocks base method
func (m *MockRepository) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), id)
}

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// GetMusica mocks base method
func (m *MockUseCase) GetMusica(id int) (*musica.Musica, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMusica", id)
	ret0, _ := ret[0].(*musica.Musica)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMusica indicates an expected call of GetMusica
func (mr *MockUseCaseMockRecorder) GetMusica(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMusica", reflect.TypeOf((*MockUseCase)(nil).GetMusica), id)
}

// SearchMusicas mocks base method
func (m *MockUseCase) SearchMusicas(query string) ([]*musica.Musica, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMusicas", query)
	ret0, _ := ret[0].([]*musica.Musica)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMusicas indicates an expected call of SearchMusicas
func (mr *MockUseCaseMockRecorder) SearchMusicas(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMusicas", reflect.TypeOf((*MockUseCase)(nil).SearchMusicas), query)
}

// ListMusicas mocks base method
func (m *MockUseCase) ListMusicas() ([]*musica.Musica, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMusicas")
	ret0, _ := ret[0].([]*musica.Musica)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMusicas indicates an expected call of ListMusicas
func (mr *MockUseCaseMockRecorder) ListMusicas() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMusicas", reflect.TypeOf((*MockUseCase)(nil).ListMusicas))
}

// CreateMusica mocks base method
func (m *MockUseCase) CreateMusica(id, duracao int, nome string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMusica", id, duracao, nome)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMusica indicates an expected call of CreateMusica
func (mr *MockUseCaseMockRecorder) CreateMusica(id, duracao, nome interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMusica", reflect.TypeOf((*MockUseCase)(nil).CreateMusica), id, duracao, nome)
}

// UpdateMusica mocks base method
func (m *MockUseCase) UpdateMusica(e *musica.Musica) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMusica", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMusica indicates an expected call of UpdateMusica
func (mr *MockUseCaseMockRecorder) UpdateMusica(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMusica", reflect.TypeOf((*MockUseCase)(nil).UpdateMusica), e)
}

// DeleteMusica mocks base method
func (m *MockUseCase) DeleteMusica(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMusica", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMusica indicates an expected call of DeleteMusica
func (mr *MockUseCaseMockRecorder) DeleteMusica(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMusica", reflect.TypeOf((*MockUseCase)(nil).DeleteMusica), id)
}
