// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/relationship/artistagravarmusica/interface.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	entity "github.com/yohanalexander/deezefy-music/entity"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Gravar mocks base method
func (m_2 *MockUseCase) Gravar(a *entity.Artista, m *entity.Musica) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Gravar", a, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Gravar indicates an expected call of Gravar
func (mr *MockUseCaseMockRecorder) Gravar(a, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gravar", reflect.TypeOf((*MockUseCase)(nil).Gravar), a, m)
}

// Desgravar mocks base method
func (m_2 *MockUseCase) Desgravar(a *entity.Artista, m *entity.Musica) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Desgravar", a, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Desgravar indicates an expected call of Desgravar
func (mr *MockUseCaseMockRecorder) Desgravar(a, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Desgravar", reflect.TypeOf((*MockUseCase)(nil).Desgravar), a, m)
}
