// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/relationship/musicapossuirgenero/interface.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	entity "github.com/yohanalexander/deezefy-music/entity"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Possuir mocks base method
func (m_2 *MockUseCase) Possuir(m *entity.Musica, g *entity.Genero) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Possuir", m, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// Possuir indicates an expected call of Possuir
func (mr *MockUseCaseMockRecorder) Possuir(m, g interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Possuir", reflect.TypeOf((*MockUseCase)(nil).Possuir), m, g)
}

// Despossuir mocks base method
func (m_2 *MockUseCase) Despossuir(m *entity.Musica, g *entity.Genero) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Despossuir", m, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// Despossuir indicates an expected call of Despossuir
func (mr *MockUseCaseMockRecorder) Despossuir(m, g interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Despossuir", reflect.TypeOf((*MockUseCase)(nil).Despossuir), m, g)
}
