// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/ouvinte/interface.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	ouvinte "github.com/yohanalexander/deezefy-music/entity/ouvinte"
	reflect "reflect"
)

// MockOuvinte is a mock of Ouvinte interface
type MockOuvinte struct {
	ctrl     *gomock.Controller
	recorder *MockOuvinteMockRecorder
}

// MockOuvinteMockRecorder is the mock recorder for MockOuvinte
type MockOuvinteMockRecorder struct {
	mock *MockOuvinte
}

// NewMockOuvinte creates a new mock instance
func NewMockOuvinte(ctrl *gomock.Controller) *MockOuvinte {
	mock := &MockOuvinte{ctrl: ctrl}
	mock.recorder = &MockOuvinteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOuvinte) EXPECT() *MockOuvinteMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockOuvinte) Get(email string) (*ouvinte.Ouvinte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", email)
	ret0, _ := ret[0].(*ouvinte.Ouvinte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockOuvinteMockRecorder) Get(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOuvinte)(nil).Get), email)
}

// Search mocks base method
func (m *MockOuvinte) Search(query string) ([]*ouvinte.Ouvinte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", query)
	ret0, _ := ret[0].([]*ouvinte.Ouvinte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockOuvinteMockRecorder) Search(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockOuvinte)(nil).Search), query)
}

// List mocks base method
func (m *MockOuvinte) List() ([]*ouvinte.Ouvinte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*ouvinte.Ouvinte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockOuvinteMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOuvinte)(nil).List))
}

// Create mocks base method
func (m *MockOuvinte) Create(e *ouvinte.Ouvinte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", e)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockOuvinteMockRecorder) Create(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOuvinte)(nil).Create), e)
}

// Update mocks base method
func (m *MockOuvinte) Update(e *ouvinte.Ouvinte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockOuvinteMockRecorder) Update(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOuvinte)(nil).Update), e)
}

// Delete mocks base method
func (m *MockOuvinte) Delete(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockOuvinteMockRecorder) Delete(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOuvinte)(nil).Delete), email)
}

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockRepository) Get(email string) (*ouvinte.Ouvinte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", email)
	ret0, _ := ret[0].(*ouvinte.Ouvinte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockRepositoryMockRecorder) Get(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), email)
}

// Search mocks base method
func (m *MockRepository) Search(query string) ([]*ouvinte.Ouvinte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", query)
	ret0, _ := ret[0].([]*ouvinte.Ouvinte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockRepositoryMockRecorder) Search(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRepository)(nil).Search), query)
}

// List mocks base method
func (m *MockRepository) List() ([]*ouvinte.Ouvinte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*ouvinte.Ouvinte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List))
}

// Create mocks base method
func (m *MockRepository) Create(e *ouvinte.Ouvinte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", e)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockRepositoryMockRecorder) Create(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), e)
}

// Update mocks base method
func (m *MockRepository) Update(e *ouvinte.Ouvinte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockRepositoryMockRecorder) Update(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), e)
}

// Delete mocks base method
func (m *MockRepository) Delete(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockRepositoryMockRecorder) Delete(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), email)
}

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// GetOuvinte mocks base method
func (m *MockUseCase) GetOuvinte(email string) (*ouvinte.Ouvinte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOuvinte", email)
	ret0, _ := ret[0].(*ouvinte.Ouvinte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOuvinte indicates an expected call of GetOuvinte
func (mr *MockUseCaseMockRecorder) GetOuvinte(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOuvinte", reflect.TypeOf((*MockUseCase)(nil).GetOuvinte), email)
}

// SearchOuvintes mocks base method
func (m *MockUseCase) SearchOuvintes(query string) ([]*ouvinte.Ouvinte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchOuvintes", query)
	ret0, _ := ret[0].([]*ouvinte.Ouvinte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchOuvintes indicates an expected call of SearchOuvintes
func (mr *MockUseCaseMockRecorder) SearchOuvintes(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchOuvintes", reflect.TypeOf((*MockUseCase)(nil).SearchOuvintes), query)
}

// ListOuvintes mocks base method
func (m *MockUseCase) ListOuvintes() ([]*ouvinte.Ouvinte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOuvintes")
	ret0, _ := ret[0].([]*ouvinte.Ouvinte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOuvintes indicates an expected call of ListOuvintes
func (mr *MockUseCaseMockRecorder) ListOuvintes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOuvintes", reflect.TypeOf((*MockUseCase)(nil).ListOuvintes))
}

// CreateOuvinte mocks base method
func (m *MockUseCase) CreateOuvinte(usuario, primeironome, sobrenome string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOuvinte", usuario, primeironome, sobrenome)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOuvinte indicates an expected call of CreateOuvinte
func (mr *MockUseCaseMockRecorder) CreateOuvinte(usuario, primeironome, sobrenome interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOuvinte", reflect.TypeOf((*MockUseCase)(nil).CreateOuvinte), usuario, primeironome, sobrenome)
}

// UpdateOuvinte mocks base method
func (m *MockUseCase) UpdateOuvinte(e *ouvinte.Ouvinte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOuvinte", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOuvinte indicates an expected call of UpdateOuvinte
func (mr *MockUseCaseMockRecorder) UpdateOuvinte(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOuvinte", reflect.TypeOf((*MockUseCase)(nil).UpdateOuvinte), e)
}

// DeleteOuvinte mocks base method
func (m *MockUseCase) DeleteOuvinte(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOuvinte", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOuvinte indicates an expected call of DeleteOuvinte
func (mr *MockUseCaseMockRecorder) DeleteOuvinte(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOuvinte", reflect.TypeOf((*MockUseCase)(nil).DeleteOuvinte), email)
}
