// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/perfil/interface.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	perfil "github.com/yohanalexander/deezefy-music/entity/perfil"
	reflect "reflect"
)

// MockPerfil is a mock of Perfil interface
type MockPerfil struct {
	ctrl     *gomock.Controller
	recorder *MockPerfilMockRecorder
}

// MockPerfilMockRecorder is the mock recorder for MockPerfil
type MockPerfilMockRecorder struct {
	mock *MockPerfil
}

// NewMockPerfil creates a new mock instance
func NewMockPerfil(ctrl *gomock.Controller) *MockPerfil {
	mock := &MockPerfil{ctrl: ctrl}
	mock.recorder = &MockPerfilMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPerfil) EXPECT() *MockPerfilMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockPerfil) Get(id int) (*perfil.Perfil, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*perfil.Perfil)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockPerfilMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPerfil)(nil).Get), id)
}

// Search mocks base method
func (m *MockPerfil) Search(query string) ([]*perfil.Perfil, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", query)
	ret0, _ := ret[0].([]*perfil.Perfil)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockPerfilMockRecorder) Search(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockPerfil)(nil).Search), query)
}

// List mocks base method
func (m *MockPerfil) List() ([]*perfil.Perfil, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*perfil.Perfil)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockPerfilMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPerfil)(nil).List))
}

// Create mocks base method
func (m *MockPerfil) Create(e *perfil.Perfil) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", e)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockPerfilMockRecorder) Create(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPerfil)(nil).Create), e)
}

// Update mocks base method
func (m *MockPerfil) Update(e *perfil.Perfil) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockPerfilMockRecorder) Update(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPerfil)(nil).Update), e)
}

// Delete mocks base method
func (m *MockPerfil) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockPerfilMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPerfil)(nil).Delete), id)
}

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockRepository) Get(id int) (*perfil.Perfil, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*perfil.Perfil)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockRepositoryMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), id)
}

// Search mocks base method
func (m *MockRepository) Search(query string) ([]*perfil.Perfil, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", query)
	ret0, _ := ret[0].([]*perfil.Perfil)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockRepositoryMockRecorder) Search(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRepository)(nil).Search), query)
}

// List mocks base method
func (m *MockRepository) List() ([]*perfil.Perfil, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*perfil.Perfil)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List))
}

// Create mocks base method
func (m *MockRepository) Create(e *perfil.Perfil) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", e)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockRepositoryMockRecorder) Create(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), e)
}

// Update mocks base method
func (m *MockRepository) Update(e *perfil.Perfil) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockRepositoryMockRecorder) Update(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), e)
}

// Delete mocks base method
func (m *MockRepository) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), id)
}

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// GetPerfil mocks base method
func (m *MockUseCase) GetPerfil(id int) (*perfil.Perfil, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPerfil", id)
	ret0, _ := ret[0].(*perfil.Perfil)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPerfil indicates an expected call of GetPerfil
func (mr *MockUseCaseMockRecorder) GetPerfil(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPerfil", reflect.TypeOf((*MockUseCase)(nil).GetPerfil), id)
}

// SearchPerfils mocks base method
func (m *MockUseCase) SearchPerfils(query string) ([]*perfil.Perfil, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPerfils", query)
	ret0, _ := ret[0].([]*perfil.Perfil)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPerfils indicates an expected call of SearchPerfils
func (mr *MockUseCaseMockRecorder) SearchPerfils(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPerfils", reflect.TypeOf((*MockUseCase)(nil).SearchPerfils), query)
}

// ListPerfils mocks base method
func (m *MockUseCase) ListPerfils() ([]*perfil.Perfil, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPerfils")
	ret0, _ := ret[0].([]*perfil.Perfil)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPerfils indicates an expected call of ListPerfils
func (mr *MockUseCaseMockRecorder) ListPerfils() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPerfils", reflect.TypeOf((*MockUseCase)(nil).ListPerfils))
}

// CreatePerfil mocks base method
func (m *MockUseCase) CreatePerfil(ouvinte, informacoesrelevantes string, id int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePerfil", ouvinte, informacoesrelevantes, id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePerfil indicates an expected call of CreatePerfil
func (mr *MockUseCaseMockRecorder) CreatePerfil(ouvinte, informacoesrelevantes, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePerfil", reflect.TypeOf((*MockUseCase)(nil).CreatePerfil), ouvinte, informacoesrelevantes, id)
}

// UpdatePerfil mocks base method
func (m *MockUseCase) UpdatePerfil(e *perfil.Perfil) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePerfil", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePerfil indicates an expected call of UpdatePerfil
func (mr *MockUseCaseMockRecorder) UpdatePerfil(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePerfil", reflect.TypeOf((*MockUseCase)(nil).UpdatePerfil), e)
}

// DeletePerfil mocks base method
func (m *MockUseCase) DeletePerfil(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePerfil", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePerfil indicates an expected call of DeletePerfil
func (mr *MockUseCaseMockRecorder) DeletePerfil(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePerfil", reflect.TypeOf((*MockUseCase)(nil).DeletePerfil), id)
}
